### ISSUE TITLE
[建议]无限阅读脚本功能增加

### ISSUE THREAD

**Issue by Chunbear** [IronKinoko/userscripts#1]
能否增加一个按住某个键可以停止加载的功能呢？

**Comment by IronKinoko** [comment]
是 e-hentai-infinite-scroll 脚本吗？
不太能理解你描述的功能是什么样子的。是遇到什么情况需要去停止加载呢？

**Comment by Chunbear** [comment]
不好意思没有表达清楚，是e-hentai-infinite-scroll 脚本，有时候看图集时希望能用到下面的功能 

![image](https://user-images.githubusercontent.com/34836688/182419928-5780528e-5896-43dc-9de4-43f0f7c1066b.png)
以下载原图为例，希望能够按或者按住某个键，比如alt之类的，让脚本暂时停止加载下一页，点击下载原图后滚动滚轮来继续浏览下面的图。
感谢你的回复！

**Comment by IronKinoko** [comment]
ok 基本理解了，是想要能去操作底部的这些功能。我有空的时候处理完再通知你。

**Comment by IronKinoko** [comment]
处理完了，鼠标移动到页面下方，底部就会出现当前页的相关操作

[点这重装脚本](https://github.com/IronKinoko/userscripts/raw/dist/e-hentai-infinite-scroll.user.js)

**Comment by Chunbear** [comment]
非常感谢！
