### ISSUE TITLE
好像是不起作用了

### ISSUE THREAD

**Issue by Chunbear** [IronKinoko/userscripts#2]
### 脚本名称

e-hentai-infinite-scroll

### 简要描述下问题

![image](https://github.com/IronKinoko/userscripts/assets/34836688/9cdf2013-240d-4c93-8dfc-e2eb6e739c52)
控制台会报一个这样的错误。
![image](https://github.com/IronKinoko/userscripts/assets/34836688/eebbf819-d140-4b7b-8c9e-da39614f58b7)

**Comment by IronKinoko** [comment]
已修复 [GitHub](https://github.com/IronKinoko/userscripts/raw/dist/e-hentai-infinite-scroll.user.js) | [greasyfork](https://greasyfork.org/scripts/451741)
